version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - /Users/fandeich/psqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_radio_counter
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fandeichdani@gmail.com
      PGADMIN_DEFAULT_PASSWORD: fandeich1987!
    ports:
      - 5050:80

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"